Repository fastn-stack/fastn, pull requests merged in 2023-11, with the labels that each got.

#1447 fixed breakpoint-width for ftd.document
  fastn-js/js/dom.js
  fastn-js/src/property.rs
  ftd/src/js/element.rs
Labels: In Review

#1460 backwards compatibility for package-query
  fastn-core/src/library2022/mod.rs
  fastn-core/src/library2022/processor/mod.rs
  fastn-core/src/library2022/processor/package_query.rs
  fastn-core/src/library2022/processor/sqlite.rs
  fastn-core/src/library2022/utils.rs
Labels: In Progress

#1473 fixed $loop$ invocation issue inside ftd.ui lists
  ftd/src/ast/kind.rs
  ftd/src/ast/utils.rs
  ftd/t/ast/16-ui-list.json
  ftd/t/js/73-loops-inside-list.ftd
  ftd/t/js/73-loops-inside-list.html
Labels: In Review, Ready to Merge

#1507 minor endpoint fix
  fastn-core/src/config/utils.rs
Labels: Testing in progress
